module.exports = {//서버들끼리의 원활한 소통을 위해서 응답메세지를 통일
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "파라미터 값이 잘못되었습니다",
    ID_OR_PW_NULL_VALUE: "아이디/비밀번호 값이 없습니다.",
    CREATED_USER: "회원 가입 성공",
    DELETE_USER: "회원 탈퇴 성공",

    ALREADY_USER: "이미 회원입니다.",
    NO_USER: "존재하지 않는 회원입니다.",
    MISS_MATCH_PW: "비밀번호가 맞지 않습니다.",
    LOGIN_SUCCESS: "로그인 성공",
    LOGIN_FAIL: "로그인 실패",
    CSV:"csv파일 성공",
    READ_FAIL:"csv 읽기 실패",
    STUDENT_SELECT_SUCCESS:"학번 일치 학생 존재",
    NO_STUDENT:"학번 일치 학생 없음",
    SAVE_SUCCESS:"csv 파일 작성 완료",
    SAVE_FAIL:"csv 파일 작성 실패",
    ALREADY_BOARD:"이미 작성된 게시글입니다.",
    BOARD_SELECT_SUCCESS:"id일치 게시글 존재",
    NO_BOARD:"id일치 게시글 없음",
    CANNOT_LOAD_BOARD:"게시글 없음",
    BOARD_CHANGE_SUCCESS:"게시글 수정 완료",
    BOARD_DELETE_SUCCESS:"게시글 삭제 완료",
    BOARD_SAVE_SUCCESS:"게시글 저장 완료",
    BOARD_SAVE_FAIL:"게시글 저장 실패",
    QUERY_SELECT_SUCCESS:"db select 성공",
    NO_GENDER:"해당하는 gender값 없음",
    NO_CONNECTION:"connection query 실패",
    SIGNUP_FAIL:"회원가입 실패(id 이미 존재)",
    USER_INSERT_FAIL:'회원가입 실패(user table insert fail)',
    USER_INSERT_SUCCESS:'회원가입 성공',
    USER_SELECT_FAIL:"게시물 불러오기 실패",
    USER_SELECT_SUCCESS:"게시물 불러오기 성공",
    BOARD_DELETE_FAIL:"게시물 삭제 실패",
    NEWS_INSERT_FAIL:"news insert 실패",
    NEWS_INSERT_SUCCESS:"news insert 성공",
    NEWSINFO_INSERT_FAIL:"newsinfo insert 실패",
    NEWSINFO_INSERT_SUCCESS:"newsinfo insert 성공",
    NEWS_SELECT_SUCCESS:"게시물 불러오기 성공",
    NEWS_SELECT_FAIL:"게시물 불러오기 실패",
    NEWSIDX_SELECT_FAIL:"일치하는 userIdx 없음",
    ALL_WEBTOON_SELECT_FAIL:"모든 웹툰 불러오기 실패",
    ALL_WEBTOON_SELECT_SUCCESS:"모든 웹툰 불러오기 성공",
    POPULAR_SORT_FAIL:"인기순 정렬 실패",
    POPULAR_SORT_SUCCESS:"인기순 정렬 성공",
    NEW_SELECT_FAIL:"신작 선택 실패",
    NEW_SELECT_SUCCESS:"신작 선택 성공",
    COMPLETE_SELECT_FAIL:"완결 선택 실패",
    COMPLETE_SELECT_SUCCESS:"완결 선택 성공",
    EPISODE_SELECT_FAIL:"웹툰별 회차 선택 실패",
    EPISODE_SELECT_SUCCESS:"웹툰별 회차 선택 성공",
    EPISODE_IMAGES_SELECT_FAIL:"회차별 이미지 선택 실패",
    EPISODE_IMAGES_SELECT_SUCCESS:"회차별 이미지 선택 성공",
    COMMENT_INSERT_FAIL:"COMMENT 삽입 실패",
    COMMENT_INSERT_SUCCESS:"COMMENT 삽입 성공",
    COMMENT_SELECT_FAIL:"회차별 COMMENT 선택 실패",
    COMMENT_SELECT_SUCCESS:"회차별 COMMENT 선택 성공",
    WEBTOON_ALL_INSERT_FAIL:"webtoon_all insert 실패",
    WEBTOON_ALL_INSERT_SUCCESS:"webtoon_all insert 성공",
    LIKE_SELECT_FAIL:"like select 실패",
    LIKE_SELECT_SUCCESS:"like select 성공",
    LIKE_UPDATE_FAIL:"like update 실패",
    LIKE_UPDATE_SUCCESS:"like update 성공",
    EPISODE_INSERT_FAIL:"webtoon_each insert 실패",
    EPISODE_INSERT_SUCCESS:"webtoon_each insert 성공",
    VIEWS_SELECT_FAIL:"each_views select 실패",
    VIEWS_SELECT_SUCCESS:"each_views select 성공",
    VIEWS_UPDATE_FAIL:"each_views update 실패",
    VIEWS_UPDATE_SUCCESS:"each_views update 성공",
    IMAGES_INSERT_FAIL:"images insert 실패",
    IMAGES_INSERT_SUCCESS:"images insert 성공",
    BANNER_SUCCESS:"banner사진 통신 성공",
    LIKE_INSERT_FAIL:"like table insert 실패",
    LIKE_DELETE_FAIL:"like table delete 실패",
    NO_LIKE:"해당 웹툰에 대해 like를 누르지 않았다",
    YES_LIKE:"해당 웹툰에 대해 like를 눌렀다",

};